### ISSUE TITLE
Unit testing for user authentication

### ISSUE THREAD

**Issue by chrisanhthien** [JayC-SF/GoVite.Inc-SOEN341_Project_F24#174]
As a dev,
I would like to create unit testing for user authentication feature,
So that I can ensure the quality of the authentication features (sign up, sign in, sign out)

**Comment by cl4414** [comment]
To run the unit test on the frontend

1. cd to the frontend
2. npm run test
3. tests must passed like in the following pic

![image](https://github.com/user-attachments/assets/2f643d01-8cb7-44cc-921e-3e0948ce2493)
