### ISSUE TITLE
Implement Downloadable for Summary View

### ISSUE THREAD

**Issue by LamdaDev** [JayC-SF/GoVite.Inc-SOEN341_Project_F24#203]
### Description

This User Story implements the second functionality for Sprint 4. We need a download button at the end of the table of the Summary View that will convert the HTML table to a CSV file directly and have it downloaded on your PC. Format of the CSV is up to you

Refer to this for documentation: https://chatgpt.com/share/6737c621-bc80-8004-8dfa-9b8fc7b11ef0

**Comment by cl4414** [comment]
This is what user sees:
![image](https://github.com/user-attachments/assets/0e15626b-9610-454d-965c-f6441e92471b)

Once click on the download button, a pop up shows:
![image](https://github.com/user-attachments/assets/bb20b87f-0c14-4e4a-9d5a-441d800b7700)

result:
![image](https://github.com/user-attachments/assets/b3b8bb96-ba26-4e0c-8733-8552d0bb555a)

Files are based in the following format:
![image](https://github.com/user-attachments/assets/ea196491-2a37-48cd-8b6e-b7a427a327d1)
