### ISSUE TITLE
Create Test Plan & Test Cases 

### ISSUE THREAD

**Issue by chrisanhthien** [JayC-SF/GoVite.Inc-SOEN341_Project_F24#36]
As a QA/Developer, I would like to create a test plan for the project.

In this ticket, it is required to:
- [ ] Create a testing plan
- [ ] Create test cases for different features, including test cases description, acceptance criteria, steps, priority.

**Comment by LamdaDev** [comment]
Just double checking on this issue. Can you add a brief description of this issue as I am unsure what is the purpose of this user story?

**Comment by chrisanhthien** [comment]
This issue is not a user story. it is an issue that is not in this sprint, but rather for later sprint. In this folder, we will be adding testing plans. It is why it is in backlog but not in Sprint 1.
