### ISSUE TITLE
Create Redirect Links for some Sidebar Buttons

### ISSUE THREAD

**Issue by LamdaDev** [JayC-SF/GoVite.Inc-SOEN341_Project_F24#87]
### Description
The purpose of the Sidebar is to allow logged in users to view many different pages inside the Dashboard page, however these redirect links have not been implemented yet. We need to implement these redirect links to redirect the user to the correct page based on what the user has clicked.

- Redirect to main
- Redirect to home
- Log out

Remain Classes, Groups, Assessment page to be redirected in Sprint 3

**Comment by cl4414** [comment]
Also, confirmation message for the form once submitted is added (Issue #115). 
Student footer was added (Issue #46).
