### ISSUE TITLE
Retrieve the list of groups for a specific class

### ISSUE THREAD

**Issue by JayC-SF** [JayC-SF/GoVite.Inc-SOEN341_Project_F24#88]
As a user,
I would like to see a group/groups displaying when I access to a class
So that I can access to group's members from this this of class

### Requirements
- [ ] Teachers can see all groups
- [ ] Students can only see their group

### Acceptance Criteria:
1. Group displaying
    a. Teacher sees all groups of a class
    b. Student sees only their group
2. Group is clickable so student can access to group members

**Comment by chrisanhthien** [comment]
This ticket is User story, not AT
